# Generated by Django 5.2.7 on 2025-10-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='kitob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kitob'),
        ),
        migrations.AlterField(
            model_name='record',
            name='kutubxonachi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kutubxonachi'),
        ),
        migrations.AlterField(
            model_name='record',
            name='talaba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.talaba'),
        ),
    ]
